"""
Abstract base class and schemas for Honey Chain AI assistance abstraction.

SECURITY & ARCHITECTURAL INVARIANTS:
- Anomaly detection uses rule-based bounds; AI provides contextual explanations and recommendations.
- AI must NOT claim disease certainty ("Possible abnormal hive condition detected", never "Disease confirmed").
- Provider credentials remain backend-only.
- If provider fails or is unconfigured, backend continues smoothly with a deterministic fallback.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class AIExplanation(BaseModel):
    """Structured AI explanation and recommended actions."""

    condition_summary: str = Field(..., description="Concise summary of current hive conditions")
    explanation: str = Field(..., description="Plain-language explanation of detected telemetry patterns")
    recommended_steps: List[str] = Field(..., description="Actionable next physical inspection steps")
    disclaimer: str = Field(
        "Possible abnormal hive condition detected. Note: Telemetry anomalies indicate "
        "environmental or behavioral variations and do NOT constitute a confirmed disease diagnosis. "
        "Physical hive inspection is required.",
        description="Non-diagnostic biological disclaimer",
    )
    is_mock: bool = Field(True, description="Whether generated by local mock provider")
    provider: str = Field("MOCK_AI", description="Provider identifier")


class AIProvider(ABC):
    """Abstract AI assistance provider."""

    @abstractmethod
    def generate_explanation(
        self,
        hive_id: int,
        hive_code: str,
        metrics_summary: Dict[str, Any],
        anomalies: List[str],
        query: Optional[str] = None,
    ) -> AIExplanation:
        """Generate plain-language explanation and inspection recommendations."""
        pass
