"""create_honey_products_and_traceability_events_tables

Revision ID: 29ed8bea9223
Revises: 055736137d0a
Create Date: 2026-09-09 10:16:06.446039+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ed8bea9223'
down_revision: Union[str, None] = '055736137d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('honey_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('trace_token', sa.String(length=64), nullable=False),
    sa.Column('net_weight_g', sa.Float(), nullable=False),
    sa.Column('packaging_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'REVOKED', 'SUSPICIOUS', name='productstatus'), nullable=False),
    sa.Column('qr_code_svg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('net_weight_g > 0', name='chk_product_net_weight_pos'),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honey_products_batch_id'), 'honey_products', ['batch_id'], unique=False)
    op.create_index(op.f('ix_honey_products_serial_number'), 'honey_products', ['serial_number'], unique=True)
    op.create_index(op.f('ix_honey_products_trace_token'), 'honey_products', ['trace_token'], unique=True)
    op.create_table('traceability_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Enum('HARVEST_RECORDED', 'BATCH_CREATED', 'PROCESSING_RECORDED', 'QUALITY_TEST_ADDED', 'PACKAGED', 'PRODUCT_CREATED', name='traceeventtype'), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('metadata_payload', sa.Text(), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('blockchain_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('is_on_chain', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['honey_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['honey_products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceability_events_batch_id'), 'traceability_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_traceability_events_event_hash'), 'traceability_events', ['event_hash'], unique=False)
    op.create_index(op.f('ix_traceability_events_product_id'), 'traceability_events', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traceability_events_product_id'), table_name='traceability_events')
    op.drop_index(op.f('ix_traceability_events_event_hash'), table_name='traceability_events')
    op.drop_index(op.f('ix_traceability_events_batch_id'), table_name='traceability_events')
    op.drop_table('traceability_events')
    op.drop_index(op.f('ix_honey_products_trace_token'), table_name='honey_products')
    op.drop_index(op.f('ix_honey_products_serial_number'), table_name='honey_products')
    op.drop_index(op.f('ix_honey_products_batch_id'), table_name='honey_products')
    op.drop_table('honey_products')
    # ### end Alembic commands ###
