"""create_iot_devices_telemetry_and_alerts_tables

Revision ID: 070444a92389
Revises: 05ba287beebe
Create Date: 2026-09-09 11:20:51.997830+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070444a92389'
down_revision: Union[str, None] = '05ba287beebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hive_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hive_devices_device_id'), 'hive_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_hive_devices_hive_id'), 'hive_devices', ['hive_id'], unique=False)
    op.create_table('hive_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('humidity_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sound_level', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('vibration_level', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('battery_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hive_telemetry_device_id'), 'hive_telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_hive_telemetry_hive_id'), 'hive_telemetry', ['hive_id'], unique=False)
    op.create_index(op.f('ix_hive_telemetry_timestamp'), 'hive_telemetry', ['timestamp'], unique=False)
    op.create_table('hive_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('telemetry_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('NORMAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['telemetry_id'], ['hive_telemetry.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hive_alerts_alert_type'), 'hive_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_hive_alerts_created_at'), 'hive_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_hive_alerts_hive_id'), 'hive_alerts', ['hive_id'], unique=False)
    op.create_index(op.f('ix_hive_alerts_severity'), 'hive_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_hive_alerts_status'), 'hive_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_hive_alerts_telemetry_id'), 'hive_alerts', ['telemetry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hive_alerts_telemetry_id'), table_name='hive_alerts')
    op.drop_index(op.f('ix_hive_alerts_status'), table_name='hive_alerts')
    op.drop_index(op.f('ix_hive_alerts_severity'), table_name='hive_alerts')
    op.drop_index(op.f('ix_hive_alerts_hive_id'), table_name='hive_alerts')
    op.drop_index(op.f('ix_hive_alerts_created_at'), table_name='hive_alerts')
    op.drop_index(op.f('ix_hive_alerts_alert_type'), table_name='hive_alerts')
    op.drop_table('hive_alerts')
    op.drop_index(op.f('ix_hive_telemetry_timestamp'), table_name='hive_telemetry')
    op.drop_index(op.f('ix_hive_telemetry_hive_id'), table_name='hive_telemetry')
    op.drop_index(op.f('ix_hive_telemetry_device_id'), table_name='hive_telemetry')
    op.drop_table('hive_telemetry')
    op.drop_index(op.f('ix_hive_devices_hive_id'), table_name='hive_devices')
    op.drop_index(op.f('ix_hive_devices_device_id'), table_name='hive_devices')
    op.drop_table('hive_devices')
    # ### end Alembic commands ###
