"""harden_iot_devices_and_telemetry_uniqueness

Revision ID: 14f59ccae3c9
Revises: 070444a92389
Create Date: 2026-09-09 15:18:13.225055+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f59ccae3c9'
down_revision: Union[str, None] = '070444a92389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hive_devices', sa.Column('device_token_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_hive_devices_device_token_hash'), 'hive_devices', ['device_token_hash'], unique=False)
    op.create_unique_constraint('uq_hive_telemetry_hive_timestamp', 'hive_telemetry', ['hive_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hive_telemetry_hive_timestamp', 'hive_telemetry', type_='unique')
    op.drop_index(op.f('ix_hive_devices_device_token_hash'), table_name='hive_devices')
    op.drop_column('hive_devices', 'device_token_hash')
    # ### end Alembic commands ###
