"""create_beekeeper_apiary_hive_harvest_batch_tables

Revision ID: 055736137d0a
Revises: 9a45a203f48a
Create Date: 2026-09-09 10:03:00.691730+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055736137d0a'
down_revision: Union[str, None] = '9a45a203f48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beekeeper_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beekeeper_code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beekeeper_profiles_beekeeper_code'), 'beekeeper_profiles', ['beekeeper_code'], unique=True)
    op.create_index(op.f('ix_beekeeper_profiles_user_id'), 'beekeeper_profiles', ['user_id'], unique=True)
    op.create_table('apiaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beekeeper_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['beekeeper_id'], ['beekeeper_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apiaries_beekeeper_id'), 'apiaries', ['beekeeper_id'], unique=False)
    op.create_table('hives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apiary_id', sa.Integer(), nullable=False),
    sa.Column('hive_code', sa.String(length=50), nullable=False),
    sa.Column('hive_type', sa.String(length=50), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REMOVED', name='hivestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['apiary_id'], ['apiaries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apiary_id', 'hive_code', name='uq_apiary_hive_code')
    )
    op.create_index(op.f('ix_hives_apiary_id'), 'hives', ['apiary_id'], unique=False)
    op.create_table('honey_harvests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hive_id', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('estimated_quantity_kg', sa.Float(), nullable=True),
    sa.Column('actual_quantity_kg', sa.Float(), nullable=False),
    sa.Column('honey_type', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_quantity_kg >= 0', name='chk_harvest_actual_qty_nonneg'),
    sa.CheckConstraint('estimated_quantity_kg IS NULL OR estimated_quantity_kg >= 0', name='chk_harvest_estimated_qty_nonneg'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honey_harvests_hive_id'), 'honey_harvests', ['hive_id'], unique=False)
    op.create_table('honey_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=False),
    sa.Column('beekeeper_id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('honey_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'READY', 'SOLD', 'RECALLED', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_kg >= 0', name='chk_batch_qty_nonneg'),
    sa.ForeignKeyConstraint(['beekeeper_id'], ['beekeeper_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['harvest_id'], ['honey_harvests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honey_batches_batch_code'), 'honey_batches', ['batch_code'], unique=True)
    op.create_index(op.f('ix_honey_batches_beekeeper_id'), 'honey_batches', ['beekeeper_id'], unique=False)
    op.create_index(op.f('ix_honey_batches_harvest_id'), 'honey_batches', ['harvest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_honey_batches_harvest_id'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_beekeeper_id'), table_name='honey_batches')
    op.drop_index(op.f('ix_honey_batches_batch_code'), table_name='honey_batches')
    op.drop_table('honey_batches')
    op.drop_index(op.f('ix_honey_harvests_hive_id'), table_name='honey_harvests')
    op.drop_table('honey_harvests')
    op.drop_index(op.f('ix_hives_apiary_id'), table_name='hives')
    op.drop_table('hives')
    op.drop_index(op.f('ix_apiaries_beekeeper_id'), table_name='apiaries')
    op.drop_table('apiaries')
    op.drop_index(op.f('ix_beekeeper_profiles_user_id'), table_name='beekeeper_profiles')
    op.drop_index(op.f('ix_beekeeper_profiles_beekeeper_code'), table_name='beekeeper_profiles')
    op.drop_table('beekeeper_profiles')
    # ### end Alembic commands ###
